export const CATEGORY_ORDER = [
    'Projects',
    'PaperReview',
    'AI',
    'proteomics',
    'Proteomics',
    'Docker',
    'Computer Science',
    'DataStructure',
    'Algorithms',
    'Linux',
    'Hackathon',
    'Toy_Projects',
    'Research',
];

export const CATEGORY_DISPLAY_NAMES: Record<string, string> = {
    'AI': '🤖 AI',
    'Projects': '📖 Projects',
    'Computer Science': '💻 Computer Science',
    'DataStructure': 'Data Structure',
    'Algorithms': 'Algorithms',
    'PaperReview': '📚 Paper Review',
    'proteomics': '🧬 Proteomics',
    'Proteomics': '🧬 Proteomics',
    'Linux': 'Linux',
    'Docker': '🐳 Docker',
    'Hackathon': 'Hackathon',
    'Toy_Projects': 'Toy Projects',
    'Research': 'Research',
    'DL_ML': 'DL/ML',
    'Jetson': 'Jetson',
    'NLP': 'NLP',
    'LLM': 'LLM',
    // Add more renames here
};

export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
    'Linux': '✔️ 내가 찾아쓰려고 저장해놓는 Linux command post',
    'Docker': '✔️ Docker 환경 설정 및 사용법 정리',
    'PaperReview': '✔️ 지금까지 읽은 논문 정리 및 공유',
    'proteomics': '✔️ Proteomics & Protein Structure',
    'Proteomics': '✔️ Proteomics & Protein Structure',
    'Computer Science': '✔️ 컴퓨터 과학 관련 내용 정리',
    'DataStructure': '✔️ 자료구조란 무엇인가',
    'Algorithms': '✔️ 알고리즘 코딩 테스트 준비',
    'Projects': '✔️ 지금까지 진행한 개인 및 팀 프로젝트, Hackathon',
    'Hackathon': '✔️ 참가했던 Hackathon 회고 및 후기, 사용기술 정리',
    'Toy_Projects': '✔️ 진행한 수업이나 프로젝트를 정리한 포스트',
    'Research': '✔️ My Research',
    'AI': '✔️ Related to Artificial Intelligence',
    'DL_ML': '✔️ Deep Learning & Machine Learning Studies',
    'NLP': '✔️ What is the Natural Language Processing',
    'Jetson': '✔️ the CV Project with Jetson Nano',
    'LLM': '✔️ Large Language Model Studies',
    // Add more descriptions here
};
